services:
  web:
    build: .
    command: python3 flask_brevets.py  
    ports:
      - "5000:5000"
    volumes:
      - .:/brevets
    links:
      - db

  restapi:
    build: ./api
    command: python -u api.py
    ports:
      - "5001:5000"
    links:
      - db
    environment:
      hostname: brevets_mongodb

  db:
    image: mongo:7.0.2
    hostname: brevets_mongodb

  website:
    build: ./website
    command: python -u website.py
    ports:
      - "5002:5000"
    depends_on:
      - restapi
    environment:
      BACKEND_ADDR: restapi
      BACKEND_PORT: 5000
      


