name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/setup-python@v5

    - name: Build Docker image
      run: |
        docker build -t my-flask-app .

    - name: Run Docker container
      run: |
        docker run --name app -d my-flask-app
        sleep 10 # Wait for the container to fully start

    - name: Docker Cleanup
      run: |
        docker stop app
        docker rm app
